name: Ubuntu RDP

on:
  workflow_dispatch:
    inputs:
      hostname:
        description: 'Enter Hostname:'
        required: false
        default: ubuntu
        type: string
      username:
        description: 'Enter Username:'
        required: false
        default: user
        type: string
      password:
        description: 'Enter Password:'
        required: false
        default: root
        type: string
      Pin:
        description: 'Enter a Pin (more or equal to 6 digits)'
        required: false
        default: 123456
        type: number
      CRP:
        description: 'Visit at http://remotedesktop.google.com/headless and, copy the command after authentication'
        required: false
        type: string

env:
  hostname: ${{ inputs.hostname }}
  username: ${{ inputs.username }}
  password: ${{ inputs.password }}
  Pin: ${{ inputs.Pin }}
  CRP: ${{ inputs.CRP }}

jobs:
  build:
    name: Deploy Server
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Cleanup Junk
        run: |
          curl -L -o Cleanup.sh \
              https://raw.githubusercontent.com/Diwash0007/Ubuntu_RDP/main/Cleanup.sh
          chmod +x Cleanup.sh
          echo THIS-WONT-WORK-NO

      - name: Create Server
        run: |
          chmod +x rdp.sh
          ./rdp.sh

      - name: Keep Running
        run: |
          chmod +x running.sh
          ./running.sh
